version: '3.3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000 --verbosity 2
    container_name: backend-central-talentos
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - internal

  db:
    container_name: database-central-talentos
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --port=8855
    environment:
      - MYSQL_ROOT_PASSWORD=hello_django
      - MYSQL_DATABASE=hello_django
      - MYSQL_USER=hello_django
      - MYSQL_PASSWORD=hello_django
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    ports:
      - "8855:8855"

  # NOVO SERVIÇO PARA TESTES
  tests:
    build: ./app
    # Este comando irá rodar os testes e gerar o relatório
    # O `--fail-fast` é útil para parar no primeiro erro
    command: sh -c "coverage run manage.py test access && coverage html"
    volumes:
      - ./app/:/usr/src/app/ # Mapeia para que os relatórios fiquem na sua máquina
    env_file:
      - ./.env.dev # Use o mesmo arquivo de ambiente ou um específico para testes
    depends_on:
      - db # Garante que o banco de dados esteja pronto
    networks:
      - internal
    # entrypoint: sh -c "sleep 10 && ..." # Pode ser necessário para esperar o DB iniciar completamente
    # remove o container após a execução
    tty: true # Garante que o output seja exibido corretamente

volumes:
  mysql_data:

networks:
  internal:
    external: false